Moved classes to folders, namespaces.
eShopWorld/telemetry pull request #40
Opened 2020-11-05 14:37 UTC by nikhilgirraj

2020-11-05 15:36 UTC, tabman83 commented
Are you just moving files around? If I am understanding correctly there's no functional change in here.

2020-11-05 15:49 UTC, dawidkeshop commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +public class MessagingConfigurationExtensionsTest
Did you forget about namespace here?

2020-11-05 16:18 UTC, nikhilgirraj commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +public class MessagingConfigurationExtensionsTest
looks like I did, I'll fix it.

2020-11-05 16:42 UTC, nikhilgirraj commented
@tabman83 correct, no functional change, just organized the classes

2020-11-09 11:32 UTC, chomick commented on src/Eshopworld.Telemetry/Configuration/Extensions/MessagingConfigurationExtensions.cs
> +namespace Eshopworld.Telemetry.Configuration.Extensions
I would keep the namespace - impact not worth the effort right now

2020-11-09 11:32 UTC, chomick commented on src/Eshopworld.Telemetry/Configuration/Extensions/TelemetryConfigurationExtensions.cs
> +namespace Eshopworld.Telemetry.Configuration.Extensions
As above, would skip namespace change

2020-11-09 11:33 UTC, chomick commented on src/Tests/Eshopworld.Telemetry.Tests/Kusto/KustoOptionsBuilderTests.cs
> +namespace Eshopworld.Telemetry.Tests.Kusto
Tests should be fine, i think, as they are not used in any other places

2020-11-09 11:35 UTC, chomick commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +        public void Test_Publish_UsesTopics_WhenSetup()
A strange test naming convention :)

2020-11-09 11:37 UTC, chomick commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +            mPublisher.VerifyAll();
This will not verify your setup as you did not mark it as verifiable.
But a better way would be have explicit 'verify' here where you properly verify what params where provided in the call

2020-11-09 11:38 UTC, chomick commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +            var mPublisher = new Mock<IPublishEvents>();
You have never assigned this publisher - there is no chance it would be ever called. Instead, if the topics are not assigned, the only thing you can verify is that there was no exception.
Also, you can verify that TopicPublisher (?) is still null (e.g. some defaults were not assigned etc)

2020-11-09 11:40 UTC, chomick commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +    public class TestDomainEvent : DomainEvent
Should it be public? Can it be internal instead?

2020-11-09 11:41 UTC, chomick requested changes
Please revert the namespace changes outside of test projects + some updates in unit tests

2020-11-09 16:40 UTC, nikhilgirraj commented on src/Tests/Eshopworld.Telemetry.Tests/Configuration/Extensions/MessagingConfigurationExtensionsTest.cs
> +        public void Test_Publish_UsesTopics_WhenSetup()
Old test. I'm not sure if I should rename in this PR.

2020-11-09 16:46 UTC, nikhilgirraj commented on src/Eshopworld.Telemetry/Configuration/Extensions/MessagingConfigurationExtensions.cs
> +namespace Eshopworld.Telemetry.Configuration.Extensions
Understood.

2020-11-10 10:55 UTC, closed without merging